version: '3.8'

services:
  # MySQL Database Server
  studyhub-db:
    image: mysql:8.0
    container_name: studyhub-mysql
    restart: unless-stopped
    environment:
      # MySQL Credentials
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD:-root_password}'
      MYSQL_DATABASE: '${DB_NAME:-studyhub}'
      MYSQL_USER: '${DB_USER:-studyhub}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-studyhub_password}'

      # Performance Optimization for Development
      MYSQL_INNODB_BUFFER_POOL_SIZE: 128M
      MYSQL_INNODB_LOG_FILE_SIZE: 32M
      MYSQL_MAX_CONNECTIONS: 50
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - studyhub-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --performance-schema=OFF
      --max_connections=50
      --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Adminer - Database Management Tool
  adminer:
    image: adminer:latest
    container_name: studyhub-adminer
    restart: unless-stopped
    depends_on:
      - studyhub-db
    ports:
      - '${ADMINER_PORT:-8080}:8080'
    environment:
      ADMINER_DEFAULT_SERVER: studyhub-db
      ADMINER_DESIGN: pepa-linha
    networks:
      - studyhub-network

networks:
  studyhub-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
